name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

  # weekly upstream compatibility check
  schedule:
    - cron: "0 3 * * 1"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
